### ISSUE TITLE
ERROR in iteration1.a3m.comb

### ISSUE THREAD

**Issue by peiqi0807** [BioinfoMachineLearning/MULTICOM3#3]
- 15:38:57.765 INFO: Input file = /home/fanglf/MULTICOM3/output_final/N5_monomer_structure_refinement_avg/original_1/iteration1/iteration1.a3m.comb

- 15:38:57.766 INFO: Output file = /home/fanglf/MULTICOM3/output_final/N5_monomer_structure_refinement_avg/original_1/iteration1/iteration1.a3m

- 15:38:57.962 ERROR: - 15:38:57.962 ERROR: Error in /big/mad/hhsuite3.2.0/src/hhalignment.cpp:1244: Compress:

- 15:38:57.962 ERROR: 	sequences in /home/fanglf/MULTICOM3/output_final/N5_monomer_structure_refinement_avg/original_1/iteration1/iteration1.a3m.comb do not all have the same number of columns, 

- 15:38:57.962 ERROR: 	
e.g. first sequence and sequence MsG0080048461.01.T01.

- 15:38:57.962 ERROR: Check input format for '-M a2m' option and consider using '-M first' or '-M 50'

How to solve this situation? Thank you

**Comment by JianLiu1994** [comment]
Can you delete all the files under this directory (/home/fanglf/MULTICOM3/output_final/N5_monomer_structure_refinement_avg/original_1/iteration1/) and try to run the system again? If this still doesn't work, could you share the a3m file (/home/fanglf/MULTICOM3/output_final/N5_monomer_structure_refinement_avg/original_1/iteration1/iteration1.a3m.comb) with me?

**Comment by peiqi0807** [comment]
Sorry for the late reply. My issue has not been resolved yet. As this type of file cannot be uploaded, I have sent it to your email. Thank you.

**Comment by peiqi0807** [comment]
[Uploading iteration1.a3m.txt…]()

**Comment by JianLiu1994** [comment]
I cannot open the link in the email you sent. Can you send the file to this email: jl4mc@umsystem.edu?
